management:
  health:
    circuit-breakers:
    #circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


resilience4j:
  circuit breaker:
  #circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50 #if 50 request failed then change the status to open
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true #transition happen automatically from open to half open after 5s for ex
        waitDurationInOpenState: 5s #status change from open to half open
        permittedNumberOfCallsInHalfOpenState: 3 # allow 3 calls in half open and after 3 cals it will change to the close if success
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED


  retry:
    instances:
      userService:
        maxRetryAttempts: 5 # real time keep it as 3
        waitDuration: 10s # real time keep it as 2











